jets:
  inputs:
    - pt_btagJes
    - eta_btagJes
  labels:
    - HadronConeExclTruthLabelID
    - HadronConeExclTruthLabelPt
    #- HadronConeExclTruthLabelLxy
    - eta_btagJes
    - pt
    - eta
    - mass
    - n_tracks_loose
    - n_truth_promptLepton

tracks:
  inputs:
    - d0
    - z0SinTheta
    - dphi
    - deta
    - qOverP
    - IP3D_signed_d0_significance
    - IP3D_signed_z0_significance
    - phiUncertainty
    - thetaUncertainty
    - qOverPUncertainty
    - numberOfPixelHits
    - numberOfSCTHits
    - numberOfInnermostPixelLayerHits
    - numberOfNextToInnermostPixelLayerHits
    - numberOfInnermostPixelLayerSharedHits
    - numberOfInnermostPixelLayerSplitHits
    - numberOfPixelSharedHits
    - numberOfPixelSplitHits
    - numberOfSCTSharedHits
    - numberOfPixelHoles
    - numberOfSCTHoles
    - leptonID
  labels:
    - truthOriginLabel
    - truthVertexIndex
#flow:
#  inputs:
#    - pt
#    - energy
#    - deta
#    - dphi
