name: pre-commit
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0
    # autofix
    #- uses: pre-commit-ci/lite-action@v1.0.1
    #  if: always()

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up python version
        uses: actions/setup-python@v4
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: python3 -m pip install --upgrade pip
      - run: python -m pip install -e .[dev] # install in editable mode with additional development tools
      - name: Run tests
        run: coverage run --source=upp -m pytest --show-capture=stdout
      - name: Report coverage with Codecov
        uses: codecov/codecov-action@v3
